version: '2'
services:
    web:
        build: Dockerfiles/app
        ports:
            - "80:80"
            - "8080:8080"
        depends_on:
            - mongodb
        volumes:
            - ./src:/usr/src/app
            - ./src/html:/var/www/html

    mongodb:
        build: Dockerfiles/mongodb
        volumes:
            - /data
        ports:
            - "27017:27017"